import { farmers } from "./farmers";
import type { Product } from "../types";

const [akua, kofi, ama, kwame, efua, yaw] = farmers;

/**
 * Harvest dates, anchored to the start of the current UTC day.
 *
 * These were previously derived straight from `Date.now()`, which is
 * evaluated once on the server and again on the client. Two lots cut the same
 * number of days ago ended up with different millisecond values in each
 * environment, so the freshness sort broke ties differently and the grid
 * hydrated in a different order. Flooring to midnight makes the value stable
 * for the whole day, which is all the precision a harvest date needs.
 */
const DAY_MS = 24 * 60 * 60 * 1000;
const startOfToday = Math.floor(Date.now() / DAY_MS) * DAY_MS;

function daysAgo(days: number): string {
  return new Date(startOfToday - days * DAY_MS).toISOString();
}

export const products: Product[] = [
  {
    id: "p1",
    name: "Cherry Tomatoes",
    slug: "cherry-tomatoes",
    description: "Plump, sweet cherry tomatoes grown in rich volcanic soil in Aburi. Pesticide-free, harvested daily at peak ripeness.",
    price: 18,
    unit: "small basket",
    minQty: 1,
    inventoryQty: 48,
    harvestDate: daysAgo(1),
    harvestAction: "picked",
    badges: ["organic", "locally-grown"],
    category: "fresh-produce",
    farmer: akua,
    images: [
      "https://images.pexels.com/photos/1327838/pexels-photo-1327838.jpeg?auto=compress&cs=tinysrgb&w=800",
      "https://images.pexels.com/photos/1327838/pexels-photo-1327838.jpeg?auto=compress&cs=tinysrgb&w=1200",
    ],
    rating: 4.8,
    reviewCount: 47,
  },
  {
    id: "p2",
    name: "Fresh Pineapple",
    slug: "fresh-pineapple",
    description: "Golden sweet MD2 pineapples from Suhum. Harvested at full ripeness, shipped same day. No artificial ripening.",
    price: 15,
    unit: "piece",
    minQty: 1,
    inventoryQty: 60,
    harvestDate: daysAgo(0.5),
    harvestAction: "cut",
    badges: ["organic", "locally-grown", "seasonal"],
    category: "fresh-produce",
    farmer: kofi,
    images: [
      "https://images.unsplash.com/photo-1550258987-190a2d41a8ba?auto=format&fit=crop&w=800&h=600",
      "https://images.pexels.com/photos/915014/pexels-photo-915014.jpeg?auto=compress&cs=tinysrgb&w=800",
    ],
    rating: 4.9,
    reviewCount: 83,
  },
  {
    id: "p3",
    name: "Garden Eggs (Aubergine)",
    slug: "garden-eggs",
    description: "Traditional Ghanaian garden eggs, perfect for stews, grilling, and salads. Grown without pesticides in Aburi.",
    price: 15,
    unit: "small basket",
    minQty: 1,
    inventoryQty: 35,
    harvestDate: daysAgo(1),
    harvestAction: "picked",
    badges: ["organic", "locally-grown"],
    category: "fresh-produce",
    farmer: akua,
    images: [
      "https://images.pexels.com/photos/28930676/pexels-photo-28930676.jpeg?auto=compress&cs=tinysrgb&w=800",
      "https://images.pexels.com/photos/36932275/pexels-photo-36932275.jpeg?auto=compress&cs=tinysrgb&w=800",
    ],
    rating: 4.6,
    reviewCount: 29,
  },
  {
    id: "p4",
    name: "Akoko Tuntum Local Chicken",
    slug: "akoko-tuntum-local-chicken",
    description: "Naturally raised Ghanaian local chicken with firm, flavourful meat for light soup, groundnut soup, jollof, and family stews. Dressed and chilled for same-day delivery.",
    price: 85,
    unit: "piece",
    minQty: 1,
    inventoryQty: 28,
    harvestDate: daysAgo(0.5),
    harvestAction: "dressed",
    badges: ["locally-grown", "eco-packaged"],
    category: "butchery",
    farmer: ama,
    images: [
      "https://images.pexels.com/photos/10842246/pexels-photo-10842246.jpeg?auto=compress&cs=tinysrgb&w=800",
      "https://images.pexels.com/photos/6281506/pexels-photo-6281506.jpeg?auto=compress&cs=tinysrgb&w=800",
    ],
    rating: 4.9,
    reviewCount: 112,
  },
  {
    id: "p5",
    name: "Akosombo Fresh Tilapia",
    slug: "akosombo-fresh-tilapia",
    description: "Whole tilapia from the Volta lake belt, cleaned on request and packed on ice. Perfect for grilled tilapia with banku, pepper, and shito.",
    price: 45,
    unit: "kg",
    minQty: 1,
    inventoryQty: 25,
    harvestDate: daysAgo(0.3),
    harvestAction: "landed",
    badges: ["locally-grown", "seasonal"],
    category: "butchery",
    farmer: kwame,
    images: [
      "https://images.pexels.com/photos/15553656/pexels-photo-15553656.jpeg?auto=compress&cs=tinysrgb&w=800",
      "https://images.pexels.com/photos/15934197/pexels-photo-15934197.jpeg?auto=compress&cs=tinysrgb&w=800",
    ],
    rating: 4.7,
    reviewCount: 54,
  },
  {
    id: "p6",
    name: "Cold-Pressed Coconut Oil",
    slug: "cold-pressed-coconut-oil",
    description: "Pure virgin coconut oil cold-pressed from sun-dried Ghanaian coconuts. Unrefined, unbleached, and packed in glass jars.",
    price: 65,
    unit: "bottle",
    minQty: 1,
    inventoryQty: 40,
    harvestDate: daysAgo(7),
    harvestAction: "pressed",
    badges: ["organic", "eco-packaged"],
    category: "eco-products",
    farmer: efua,
    images: [
      "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=800&h=600",
      "https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&w=800&h=600",
    ],
    rating: 4.8,
    reviewCount: 68,
  },
  {
    id: "p7",
    name: "Fresh Spinach",
    slug: "fresh-spinach",
    description: "Tender dark-green spinach leaves grown in raised beds in Aburi. Washed and packed in compostable bags.",
    price: 12,
    unit: "bunch",
    minQty: 1,
    inventoryQty: 55,
    harvestDate: daysAgo(0.5),
    harvestAction: "cut",
    badges: ["organic", "locally-grown", "eco-packaged"],
    category: "fresh-produce",
    farmer: akua,
    images: [
      "https://images.unsplash.com/photo-1576045057995-568f588f82fb?auto=format&fit=crop&w=800&h=600",
      "https://images.pexels.com/photos/1435904/pexels-photo-1435904.jpeg?auto=compress&cs=tinysrgb&w=800",
    ],
    rating: 4.7,
    reviewCount: 41,
  },
  {
    id: "p8",
    name: "Red Bell Peppers",
    slug: "red-bell-peppers",
    description: "Crisp, sweet red bell peppers bursting with vitamin C. Grown without pesticides, perfect for salads, stir fries, and stews.",
    price: 20,
    unit: "small basket",
    minQty: 1,
    inventoryQty: 42,
    harvestDate: daysAgo(1),
    harvestAction: "picked",
    badges: ["organic", "locally-grown"],
    category: "fresh-produce",
    farmer: akua,
    images: [
      "https://images.pexels.com/photos/128536/pexels-photo-128536.jpeg?auto=compress&cs=tinysrgb&w=800",
      "https://images.pexels.com/photos/1435904/pexels-photo-1435904.jpeg?auto=compress&cs=tinysrgb&w=800",
    ],
    rating: 4.6,
    reviewCount: 33,
  },
  {
    id: "p9",
    name: "Fresh Pawpaw (Papaya)",
    slug: "fresh-pawpaw",
    description: "Sun-ripened pawpaw with deep orange flesh and natural sweetness. Rich in digestive enzymes. From Kofi's Suhum farm.",
    price: 20,
    unit: "piece",
    minQty: 1,
    inventoryQty: 30,
    harvestDate: daysAgo(1),
    harvestAction: "picked",
    badges: ["organic", "locally-grown", "seasonal"],
    category: "fresh-produce",
    farmer: kofi,
    images: [
      "https://images.unsplash.com/photo-1601493700631-2b16ec4b4716?auto=format&fit=crop&w=800&h=600",
    ],
    rating: 4.5,
    reviewCount: 22,
  },
  {
    id: "p10",
    name: "Yam (Puna)",
    slug: "yam-puna",
    description: "Heritage Puna yam grown using traditional methods in Akropong. No fertilisers, dense and flavourful — the real thing.",
    price: 35,
    unit: "tuber",
    minQty: 1,
    inventoryQty: 70,
    harvestDate: daysAgo(3),
    harvestAction: "lifted",
    badges: ["locally-grown", "seasonal"],
    category: "nuts-pantry",
    farmer: yaw,
    images: [
      "https://images.pexels.com/photos/34143558/pexels-photo-34143558.jpeg?auto=compress&cs=tinysrgb&w=800",
      "https://images.pexels.com/photos/12714976/pexels-photo-12714976.jpeg?auto=compress&cs=tinysrgb&w=800",
    ],
    rating: 4.8,
    reviewCount: 58,
  },
  {
    id: "p11",
    name: "Mango (Keitt)",
    slug: "mango-keitt",
    description: "Large Keitt mangoes with creamy, fibre-free flesh and irresistible sweetness. Harvested at peak season from Kofi's farm.",
    price: 8,
    unit: "piece",
    minQty: 3,
    inventoryQty: 45,
    harvestDate: daysAgo(0.5),
    harvestAction: "picked",
    badges: ["organic", "locally-grown", "seasonal"],
    category: "fresh-produce",
    farmer: kofi,
    images: [
      "https://images.unsplash.com/photo-1601493700631-2b16ec4b4716?auto=format&fit=crop&w=800&h=600",
      "https://images.unsplash.com/photo-1519096845289-95806ee03a1a?auto=format&fit=crop&w=800&h=600",
    ],
    rating: 4.9,
    reviewCount: 97,
  },
  {
    id: "p12",
    name: "Raw Shea Butter",
    slug: "raw-shea-butter",
    description: "Unrefined Grade A shea butter from northern Ghana. Cold-processed to preserve all nutrients. Packaged in reusable glass jars.",
    price: 55,
    unit: "pack",
    minQty: 1,
    inventoryQty: 35,
    harvestDate: daysAgo(14),
    harvestAction: "made",
    badges: ["organic", "eco-packaged"],
    category: "eco-products",
    farmer: efua,
    images: [
      "https://images.pexels.com/photos/11284698/pexels-photo-11284698.jpeg?auto=compress&cs=tinysrgb&w=800",
      "https://images.pexels.com/photos/4735913/pexels-photo-4735913.jpeg?auto=compress&cs=tinysrgb&w=800",
    ],
    rating: 4.8,
    reviewCount: 44,
  },
  {
    id: "p13",
    name: "Plantain (Yellow)",
    slug: "plantain-yellow",
    description: "Perfectly ripe yellow plantain, sweet and ready for kelewele or frying. Grown on the lush Eastern Region plains.",
    price: 3,
    unit: "finger",
    minQty: 5,
    inventoryQty: 90,
    harvestDate: daysAgo(2),
    harvestAction: "cut",
    badges: ["locally-grown"],
    category: "fresh-produce",
    farmer: yaw,
    images: [
      "https://images.pexels.com/photos/1093038/pexels-photo-1093038.jpeg?auto=compress&cs=tinysrgb&w=800",
    ],
    rating: 4.7,
    reviewCount: 75,
  },
  {
    id: "p14",
    name: "Fresh Cucumber",
    slug: "fresh-cucumber",
    description: "Crisp, cool cucumbers with thin skin and barely any seeds. Ideal for salads, juicing, and cooling summer dishes.",
    price: 8,
    unit: "piece",
    minQty: 2,
    inventoryQty: 120,
    harvestDate: daysAgo(0.5),
    harvestAction: "picked",
    badges: ["organic", "locally-grown"],
    category: "fresh-produce",
    farmer: akua,
    images: [
      "https://images.unsplash.com/photo-1449300079323-02e209d9d3a6?auto=format&fit=crop&w=800&h=600",
    ],
    rating: 4.5,
    reviewCount: 19,
  },
  {
    id: "p15",
    name: "Groundnuts (Roasted)",
    slug: "groundnuts-roasted",
    description: "Freshly roasted Ghanaian groundnuts, lightly salted. Perfect snacking, groundnut soup base, or homemade peanut butter.",
    price: 35,
    unit: "paint rubber",
    minQty: 1,
    inventoryQty: 60,
    harvestDate: daysAgo(5),
    harvestAction: "roasted",
    badges: ["locally-grown", "eco-packaged"],
    category: "nuts-pantry",
    farmer: yaw,
    images: [
      "https://images.pexels.com/photos/34143551/pexels-photo-34143551.jpeg?auto=compress&cs=tinysrgb&w=800",
      "https://images.pexels.com/photos/35869518/pexels-photo-35869518.jpeg?auto=compress&cs=tinysrgb&w=800",
    ],
    rating: 4.6,
    reviewCount: 38,
  },
  {
    id: "p16",
    name: "Kpong Smoked Catfish",
    slug: "kpong-smoked-catfish",
    description: "Ghanaian smoked catfish with deep savoury flavour for abenkwan, light soup, kontomire stew, okro stew, and fufu. Cleaned, smoked, and sealed for freshness.",
    price: 58,
    unit: "kg",
    minQty: 0.5,
    inventoryQty: 24,
    harvestDate: daysAgo(0.5),
    harvestAction: "smoked",
    badges: ["locally-grown", "seasonal"],
    category: "butchery",
    farmer: kwame,
    images: [
      "https://images.pexels.com/photos/15934197/pexels-photo-15934197.jpeg?auto=compress&cs=tinysrgb&w=800",
      "https://images.pexels.com/photos/15553656/pexels-photo-15553656.jpeg?auto=compress&cs=tinysrgb&w=800",
    ],
    rating: 4.7,
    reviewCount: 31,
  },
  {
    id: "p17",
    name: "Moringa Powder",
    slug: "moringa-powder",
    description: "Sun-dried and stone-ground moringa leaf powder. Dense in vitamins and minerals. No additives, packed in compostable sachets.",
    price: 45,
    unit: "pack",
    minQty: 1,
    inventoryQty: 55,
    harvestDate: daysAgo(10),
    harvestAction: "milled",
    badges: ["organic", "eco-packaged"],
    category: "eco-products",
    farmer: efua,
    images: [
      "https://images.pexels.com/photos/7149595/pexels-photo-7149595.jpeg?auto=compress&cs=tinysrgb&w=800",
      "https://images.pexels.com/photos/1313431/pexels-photo-1313431.jpeg?auto=compress&cs=tinysrgb&w=800",
    ],
    rating: 4.9,
    reviewCount: 52,
  },
  {
    id: "p18",
    name: "Ginger Root",
    slug: "ginger-root",
    description: "Fiery fresh ginger root grown organically in Aburi. Essential for Ghanaian cooking, teas, and wellness drinks.",
    price: 12,
    unit: "small basket",
    minQty: 1,
    inventoryQty: 65,
    harvestDate: daysAgo(2),
    harvestAction: "lifted",
    badges: ["organic", "locally-grown"],
    category: "fresh-produce",
    farmer: akua,
    images: [
      "https://images.pexels.com/photos/161556/ginger-plant-asia-rhizome-161556.jpeg?auto=compress&cs=tinysrgb&w=800",
    ],
    rating: 4.7,
    reviewCount: 61,
  },
  {
    id: "p19",
    name: "Cassava (White)",
    slug: "cassava-white",
    description: "Starchy white cassava roots from Akropong, grown using traditional methods. Perfect for fufu, gari, ampesi, and more.",
    price: 8,
    unit: "tuber",
    minQty: 1,
    inventoryQty: 100,
    harvestDate: daysAgo(3),
    harvestAction: "lifted",
    badges: ["locally-grown"],
    category: "nuts-pantry",
    farmer: yaw,
    images: [
      "https://images.pexels.com/photos/9568902/pexels-photo-9568902.jpeg?auto=compress&cs=tinysrgb&w=800",
      "https://images.pexels.com/photos/27397338/pexels-photo-27397338.jpeg?auto=compress&cs=tinysrgb&w=800",
    ],
    rating: 4.5,
    reviewCount: 27,
  },
  {
    id: "p20",
    name: "Fresh Orange (Jaffa)",
    slug: "fresh-orange",
    description: "Juicy Jaffa oranges from Suhum — sweeter than anything imported. Vitamin-packed and bursting with natural citrus flavour.",
    price: 30,
    unit: "small basket",
    minQty: 1,
    inventoryQty: 75,
    harvestDate: daysAgo(1),
    harvestAction: "picked",
    badges: ["organic", "locally-grown", "seasonal"],
    category: "fresh-produce",
    farmer: kofi,
    images: [
      "https://images.pexels.com/photos/42059/citrus-diet-food-fresh-42059.jpeg?auto=compress&cs=tinysrgb&w=800",
      "https://images.unsplash.com/photo-1582979512210-99b6a53386f9?auto=format&fit=crop&w=800&h=600",
    ],
    rating: 4.8,
    reviewCount: 45,
  },
  {
    id: "p21",
    name: "Grass-Fed Goat Meat",
    slug: "grass-fed-goat-meat",
    description: "Fresh Ghanaian goat meat cut for light soup, pepper soup, jollof, waakye stew, and weekend grilling. Lean, flavourful, and packed in chilled portions.",
    price: 72,
    unit: "kg",
    minQty: 0.5,
    inventoryQty: 38,
    harvestDate: daysAgo(0.5),
    harvestAction: "dressed",
    badges: ["locally-grown", "bulk-available"],
    category: "butchery",
    farmer: ama,
    images: [
      "https://images.pexels.com/photos/6281507/pexels-photo-6281507.jpeg?auto=compress&cs=tinysrgb&w=800",
      "https://images.pexels.com/photos/13888400/pexels-photo-13888400.jpeg?auto=compress&cs=tinysrgb&w=800",
    ],
    rating: 4.8,
    reviewCount: 36,
  },
  {
    id: "p22",
    name: "Local Beef Cuts",
    slug: "local-beef-cuts",
    description: "Fresh cow meat from local cattle, trimmed into stew and soup cuts. Good for beef light soup, kontomire stew, jollof, and slow-cooked Sunday meals.",
    price: 78,
    unit: "kg",
    minQty: 0.5,
    inventoryQty: 32,
    harvestDate: daysAgo(0.5),
    harvestAction: "dressed",
    badges: ["locally-grown", "bulk-available"],
    category: "butchery",
    farmer: ama,
    images: [
      "https://images.pexels.com/photos/8477071/pexels-photo-8477071.jpeg?auto=compress&cs=tinysrgb&w=800",
      "https://images.pexels.com/photos/8112380/pexels-photo-8112380.jpeg?auto=compress&cs=tinysrgb&w=800",
    ],
    rating: 4.7,
    reviewCount: 41,
  },
  {
    id: "p23",
    name: "Sheep Meat (Mutton)",
    slug: "sheep-meat-mutton",
    description: "Tender mutton portions for rich Ghanaian soups, stews, kebabs, and festive rice dishes. Cut bone-in for deeper flavour and better stock.",
    price: 82,
    unit: "kg",
    minQty: 0.5,
    inventoryQty: 26,
    harvestDate: daysAgo(1),
    harvestAction: "dressed",
    badges: ["locally-grown", "seasonal"],
    category: "butchery",
    farmer: ama,
    images: [
      "https://images.pexels.com/photos/6281506/pexels-photo-6281506.jpeg?auto=compress&cs=tinysrgb&w=800",
      "https://images.pexels.com/photos/6281507/pexels-photo-6281507.jpeg?auto=compress&cs=tinysrgb&w=800",
    ],
    rating: 4.8,
    reviewCount: 28,
  },
  {
    id: "p24",
    name: "Farm-Raised Rabbit Meat",
    slug: "farm-raised-rabbit-meat",
    description: "Lean rabbit meat from small Ghanaian farms, dressed and chilled for healthy stews, pepper soup, grilling, or light family meals.",
    price: 68,
    unit: "kg",
    minQty: 0.5,
    inventoryQty: 18,
    harvestDate: daysAgo(1),
    harvestAction: "dressed",
    badges: ["locally-grown", "seasonal"],
    category: "butchery",
    farmer: ama,
    images: [
      "https://images.pexels.com/photos/13729827/pexels-photo-13729827.jpeg?auto=compress&cs=tinysrgb&w=800",
    ],
    rating: 4.6,
    reviewCount: 17,
  },
  {
    id: "p25",
    name: "Farm-Raised Grasscutter",
    slug: "farm-raised-grasscutter",
    description: "Licensed farm-raised grasscutter, dressed and portioned for Ghanaian light soup, palm nut soup, pepper soup, or charcoal grilling. No wild-caught or protected wildlife.",
    price: 95,
    unit: "kg",
    minQty: 0.5,
    inventoryQty: 16,
    harvestDate: daysAgo(1),
    harvestAction: "dressed",
    badges: ["locally-grown", "seasonal"],
    category: "butchery",
    farmer: ama,
    images: [
      "https://images.pexels.com/photos/13729827/pexels-photo-13729827.jpeg?auto=compress&cs=tinysrgb&w=800",
      "https://images.pexels.com/photos/6281507/pexels-photo-6281507.jpeg?auto=compress&cs=tinysrgb&w=800",
    ],
    rating: 4.8,
    reviewCount: 14,
  },
  {
    id: "p26",
    name: "Smoked Grasscutter",
    slug: "smoked-grasscutter",
    description: "Farm-raised grasscutter, smoked low and slow for deep flavour in abenkwan, groundnut soup, kontomire stew, and okro stew. Sourced only from licensed farms.",
    price: 110,
    unit: "kg",
    minQty: 0.5,
    inventoryQty: 12,
    harvestDate: daysAgo(2),
    harvestAction: "smoked",
    badges: ["locally-grown", "seasonal"],
    category: "butchery",
    farmer: ama,
    images: [
      "https://images.pexels.com/photos/6281507/pexels-photo-6281507.jpeg?auto=compress&cs=tinysrgb&w=800",
      "https://images.pexels.com/photos/13729827/pexels-photo-13729827.jpeg?auto=compress&cs=tinysrgb&w=800",
    ],
    rating: 4.9,
    reviewCount: 11,
  },
  {
    id: "p27",
    name: "Northern Guinea Fowl",
    slug: "northern-guinea-fowl",
    description: "Lean, richly flavoured guinea fowl from small northern Ghana farms. Excellent for soup, jollof, grilling, and festive family meals.",
    price: 92,
    unit: "piece",
    minQty: 1,
    inventoryQty: 20,
    harvestDate: daysAgo(0.5),
    harvestAction: "dressed",
    badges: ["locally-grown", "seasonal"],
    category: "butchery",
    farmer: ama,
    images: [
      "https://images.pexels.com/photos/4052987/pexels-photo-4052987.jpeg?auto=compress&cs=tinysrgb&w=800",
      "https://images.pexels.com/photos/29153438/pexels-photo-29153438.jpeg?auto=compress&cs=tinysrgb&w=800",
    ],
    rating: 4.8,
    reviewCount: 23,
  },
  {
    id: "p28",
    name: "Farmed Giant Snails",
    slug: "farmed-giant-snails",
    description: "Cleaned farmed giant snails, a Ghanaian delicacy for peppered snail, light soup, and palm nut soup. Purged, washed, and packed chilled.",
    price: 75,
    unit: "pack",
    minQty: 1,
    inventoryQty: 22,
    harvestDate: daysAgo(1),
    harvestAction: "gathered",
    badges: ["locally-grown", "eco-packaged", "seasonal"],
    category: "butchery",
    farmer: ama,
    images: [
      "https://images.pexels.com/photos/13189280/pexels-photo-13189280.jpeg?auto=compress&cs=tinysrgb&w=800",
      "https://images.pexels.com/photos/7474061/pexels-photo-7474061.jpeg?auto=compress&cs=tinysrgb&w=800",
    ],
    rating: 4.7,
    reviewCount: 19,
  },

  {
    id: "p38",
    name: "Raw Honey",
    slug: "raw-honey",
    description: "Unfiltered, unheated wildflower honey from small-scale beekeepers in the Brong-Ahafo region. Rich, dark amber colour, high in antioxidants and enzymes. Packed in glass jars.",
    price: 65,
    unit: "pack",
    minQty: 1,
    inventoryQty: 40,
    harvestDate: daysAgo(7),
    harvestAction: "harvested",
    badges: ["organic", "locally-grown", "eco-packaged"],
    category: "nuts-pantry",
    farmer: efua,
    images: [
      "https://images.pexels.com/photos/1638280/pexels-photo-1638280.jpeg?auto=compress&cs=tinysrgb&w=800",
      "https://images.pexels.com/photos/2796123/pexels-photo-2796123.jpeg?auto=compress&cs=tinysrgb&w=800",
    ],
    rating: 4.9,
    reviewCount: 76,
  },

  // ── Juices & Smoothies ────────────────────────────────────────────────
  {
    id: "p29",
    name: "Sobolo (Hibiscus Drink)",
    slug: "sobolo-hibiscus-drink",
    description: "Freshly brewed Sobolo made from dried red hibiscus petals, ginger, and pineapple. Cold-brewed, no preservatives, bottled same day. A Ghanaian household favourite.",
    price: 20,
    unit: "bottle",
    minQty: 1,
    inventoryQty: 60,
    harvestDate: daysAgo(0.5),
    harvestAction: "brewed",
    badges: ["organic", "locally-grown"],
    category: "juices",
    farmer: efua,
    images: [
      "https://images.pexels.com/photos/34481087/pexels-photo-34481087.jpeg?auto=compress&cs=tinysrgb&w=800",
      "https://images.pexels.com/photos/34477394/pexels-photo-34477394.jpeg?auto=compress&cs=tinysrgb&w=800",
    ],
    rating: 4.9,
    reviewCount: 88,
  },
  {
    id: "p30",
    name: "Fresh Sugarcane Juice",
    slug: "fresh-sugarcane-juice",
    description: "Cold-pressed sugarcane juice made fresh daily. Natural sweetness, no added sugar. Best served iced — a beloved Ghanaian street classic, now at your door.",
    price: 15,
    unit: "cup",
    minQty: 2,
    inventoryQty: 80,
    harvestDate: daysAgo(0.3),
    harvestAction: "pressed",
    badges: ["organic", "locally-grown"],
    category: "juices",
    farmer: kofi,
    images: [
      "https://images.pexels.com/photos/25078443/pexels-photo-25078443.jpeg?auto=compress&cs=tinysrgb&w=800",
      "https://images.pexels.com/photos/16387070/pexels-photo-16387070.jpeg?auto=compress&cs=tinysrgb&w=800",
    ],
    rating: 4.8,
    reviewCount: 64,
  },
  {
    id: "p31",
    name: "Mango Smoothie",
    slug: "mango-smoothie",
    description: "Thick, creamy smoothie blended from Keitt mangoes straight off Kofi's Suhum farm. No milk powder, no ice cream, no added sugar — pure mango, nothing else.",
    price: 22,
    unit: "bottle",
    minQty: 1,
    inventoryQty: 45,
    harvestDate: daysAgo(0.5),
    harvestAction: "blended",
    badges: ["organic", "locally-grown", "seasonal"],
    category: "juices",
    farmer: kofi,
    images: [
      "https://images.pexels.com/photos/14930492/pexels-photo-14930492.jpeg?auto=compress&cs=tinysrgb&w=800",
      "https://images.pexels.com/photos/17612822/pexels-photo-17612822.jpeg?auto=compress&cs=tinysrgb&w=800",
    ],
    rating: 4.9,
    reviewCount: 71,
  },
  {
    id: "p32",
    name: "Watermelon Juice",
    slug: "watermelon-juice",
    description: "Freshly pressed watermelon juice with a hint of ginger and lime. Made daily from locally grown watermelons — cold, hydrating, and absolutely no water added.",
    price: 18,
    unit: "bottle",
    minQty: 1,
    inventoryQty: 50,
    harvestDate: daysAgo(0.5),
    harvestAction: "pressed",
    badges: ["organic", "locally-grown"],
    category: "juices",
    farmer: kofi,
    images: [
      "https://images.pexels.com/photos/8679183/pexels-photo-8679183.jpeg?auto=compress&cs=tinysrgb&w=800",
      "https://images.pexels.com/photos/11009203/pexels-photo-11009203.jpeg?auto=compress&cs=tinysrgb&w=800",
    ],
    rating: 4.7,
    reviewCount: 53,
  },
  {
    id: "p33",
    name: "Tiger Nut Milk (Asana)",
    slug: "tiger-nut-milk-asana",
    description: "Traditional Ghanaian Asana — creamy tiger nut milk strained fresh daily. Naturally sweet, dairy-free, and rich in fibre. A northern Ghana favourite bottled for Accra.",
    price: 25,
    unit: "bottle",
    minQty: 1,
    inventoryQty: 35,
    harvestDate: daysAgo(0.5),
    harvestAction: "blended",
    badges: ["organic", "locally-grown"],
    category: "juices",
    farmer: yaw,
    images: [
      "https://images.pexels.com/photos/34298621/pexels-photo-34298621.jpeg?auto=compress&cs=tinysrgb&w=800",
      "https://images.pexels.com/photos/6803741/pexels-photo-6803741.jpeg?auto=compress&cs=tinysrgb&w=800",
    ],
    rating: 4.8,
    reviewCount: 39,
  },
  {
    id: "p34",
    name: "Tropical Fruit Smoothie",
    slug: "tropical-fruit-smoothie",
    description: "A vibrant blend of pineapple, banana, pawpaw, and passion fruit from Kofi's farm. No ice cream, no artificial flavours — just whole real fruit, blended fresh daily.",
    price: 25,
    unit: "bottle",
    minQty: 1,
    inventoryQty: 40,
    harvestDate: daysAgo(0.5),
    harvestAction: "blended",
    badges: ["organic", "locally-grown", "seasonal"],
    category: "juices",
    farmer: kofi,
    images: [
      "https://images.pexels.com/photos/6990114/pexels-photo-6990114.jpeg?auto=compress&cs=tinysrgb&w=800",
      "https://images.pexels.com/photos/16096610/pexels-photo-16096610.jpeg?auto=compress&cs=tinysrgb&w=800",
    ],
    rating: 4.9,
    reviewCount: 47,
  },

  // ── Subscription Boxes ────────────────────────────────────────────────
  {
    id: "p35",
    name: "Garden Box — Weekly",
    slug: "garden-box-weekly",
    description: "A curated weekly selection of seasonal vegetables for 2 — kontomire, garden eggs, peppers, plantain, and a surprise seasonal pick. Sourced fresh, delivered every Monday.",
    price: 85,
    unit: "box",
    minQty: 1,
    inventoryQty: 30,
    harvestDate: daysAgo(1),
    harvestAction: "packed",
    badges: ["organic", "locally-grown", "eco-packaged"],
    category: "subscription-boxes",
    farmer: akua,
    images: [
      "https://images.pexels.com/photos/5503187/pexels-photo-5503187.jpeg?auto=compress&cs=tinysrgb&w=800",
      "https://images.pexels.com/photos/7657078/pexels-photo-7657078.jpeg?auto=compress&cs=tinysrgb&w=800",
    ],
    rating: 4.8,
    reviewCount: 62,
  },
  {
    id: "p36",
    name: "Family Box — Weekly",
    slug: "family-box-weekly",
    description: "Everything a family of 4–6 needs for the week — fresh produce, fruits, herbs, and a pantry staple. Customisable. Delivered every Monday before 10am.",
    price: 160,
    unit: "box",
    minQty: 1,
    inventoryQty: 20,
    harvestDate: daysAgo(1),
    harvestAction: "packed",
    badges: ["organic", "locally-grown", "eco-packaged"],
    category: "subscription-boxes",
    farmer: akua,
    images: [
      "https://images.pexels.com/photos/4451870/pexels-photo-4451870.jpeg?auto=compress&cs=tinysrgb&w=800",
      "https://images.pexels.com/photos/7657090/pexels-photo-7657090.jpeg?auto=compress&cs=tinysrgb&w=800",
    ],
    rating: 4.9,
    reviewCount: 98,
  },
  {
    id: "p37",
    name: "Business Box — Weekly",
    slug: "business-box-weekly",
    description: "Bulk weekly supply for restaurants, hotels, and offices. Fully customisable quantities, priority Monday delivery, and a dedicated account manager. Minimum 5-week commitment.",
    price: 420,
    unit: "box",
    minQty: 1,
    inventoryQty: 10,
    harvestDate: daysAgo(1),
    harvestAction: "packed",
    badges: ["locally-grown", "eco-packaged"],
    category: "subscription-boxes",
    farmer: akua,
    images: [
      "https://images.pexels.com/photos/3978831/pexels-photo-3978831.jpeg?auto=compress&cs=tinysrgb&w=800",
      "https://images.pexels.com/photos/5503187/pexels-photo-5503187.jpeg?auto=compress&cs=tinysrgb&w=800",
    ],
    rating: 4.8,
    reviewCount: 34,
  },
];

export const getProductBySlug = (slug: string) =>
  products.find((p) => p.slug === slug);

export const getProductsByCategory = (category: string) =>
  products.filter((p) => p.category === category);

export const getFeaturedProducts = () => products.slice(0, 8);
